In [1]:
import pandas as pd
from IPython.display import display

In [2]:
def total_compra(preco, quantidade, desconto=0):
    if preco < 0 or quantidade < 0:
        raise ValueError("Preço e quantidade precisam ser não negativos.")
    if not 0 <= desconto <= 100:
        raise ValueError("Desconto precisa estar entre 0 e 100.")
    return preco * quantidade * (1 - desconto / 100)

total = total_compra(50, 2, 10)
print(total)

90.0

In [4]:
def classificar_compra(total):
    if total < 0:
        raise ValueError("Total não pode ser negativo.")
    if total < 100:
        return "Pequena"
    if total < 300:
        return "Média"
    return "Grande"

In [5]:
print(classificar_compra(90))
print(classificar_compra(100))
print(classificar_compra(300))

Pequena
Média
Grande

In [6]:
classes = []

for valor in [90, 300, 19]:
    classes.append(classificar_compra(valor))

print(classes)

['Pequena', 'Grande', 'Pequena']

In [7]:
# Cria uma lista vazia para guardar as classificações
classes = []

# Percorre cada valor da lista
for valor in [90, 300, 19]:

    # Chama a função classificar_compra()
    # e guarda o resultado dentro da lista "classes"
    classes.append(classificar_compra(valor))

# Mostra na tela a lista com as classificações
print(classes)

['Pequena', 'Grande', 'Pequena']

In [8]:
# Cria uma tabela com os dados das vendas
vendas = pd.DataFrame({
    "produto": ["A", "B", "C"],
    "preco": [50, 100, 20],
    "quantidade": [2, 3, 1],
    "desconto": [10, 0, 5]
})

# Calcula o total de cada compra
vendas["total"] = (
    vendas["preco"]
    * vendas["quantidade"]
    * (1 - vendas["desconto"] / 100)
)

# Mostra a tabela na tela
display(vendas)

  produto  preco  quantidade  desconto  total
0       A     50           2        10   90.0
1       B    100           3         0  300.0
2       C     20           1         5   19.0

In [9]:
# Cria uma nova coluna chamada "classe"
# para classificar cada compra
vendas["classe"] = vendas["total"].apply(classificar_compra)

# Mostra a tabela atualizada
display(vendas)

  produto  preco  quantidade  desconto  total   classe
0       A     50           2        10   90.0  Pequena
1       B    100           3         0  300.0   Grande
2       C     20           1         5   19.0  Pequena

In [10]:
# Cria uma função que resume uma compra
def resumir_compra(preco, quantidade, desconto=0):

    # Calcula o valor total usando a função que já criamos
    total = total_compra(preco, quantidade, desconto)

    # Retorna um dicionário com o total e a classificação
    return {
        "total": total,
        "classe": classificar_compra(total)
    }

In [11]:
# Testa a função com uma compra válida
print(resumir_compra(50, 2, 10))

{'total': 90.0, 'classe': 'Pequena'}

In [12]:
# Testa um desconto inválido: 120%
try:
    resumir_compra(50, 2, 120)

# Captura o erro esperado
except ValueError as erro:
    print("Erro esperado:", erro)

# Se nenhum erro acontecer, o programa avisa que algo está errado
else:
    raise AssertionError("Esperava rejeição de desconto inválido.")

Erro esperado: Desconto precisa estar entre 0 e 100.